language: python
python:
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install pycodestyle

script:
    - ./test_reframe.py
    - pycodestyle --ignore=E129,E221,E226,E241,E272,E722 . --exclude=docs/

