language: python
python:
    - "3.5"
    - "3.6"

jobs:
    include:
        install:
            - pip install -r requirements.txt

        script:
            ./test_reframe.py
        - stage: pep8
            install:
                - pip install pycodestyle
            python: 3.6
            script:
                pycodestyle reframe/

