# Copyright 2016-2025 Swiss National Supercomputing Centre (CSCS/ETH Zurich)
# ReFrame Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: BSD-3-Clause

services:
  database:
    image: mariadb:lts-ubi9
    hostname: mariadb
    container_name: mariadb
    environment:
      MARIADB_PASSWORD: "reframe"
      MARIADB_ROOT_PASSWORD: "my-rfm-secret"
      MARIADB_DATABASE: "rfm_slurm_db"
      MARIADB_USER: "slurm"

  munge-key-generator:
    image: ghcr.io/reframe-hpc/munge-ubuntu:22.04
    hostname: munge-host
    healthcheck:
        test: ["CMD-SHELL", "test -f /etc/munge/munge.key"]
        interval: 10s
        timeout: 10s
        retries: 5
    volumes:
      - munge-etc:/etc/munge

  slurmdbd:
    image: ghcr.io/reframe-hpc/slurm-dbd-ubuntu:22.04
    container_name: slurmdbd
    hostname: slurmdbd
    healthcheck:
        test: ["CMD-SHELL", "service slurmdbd status"]
        interval: 10s
        timeout: 10s
        retries: 5
    expose:
      - "6819"
    depends_on:
      database:
        condition: service_started
      munge-key-generator:
        condition: service_healthy
    links:
      - database
    volumes:
      - munge-etc:/etc/munge/
      - slurm-etc:/etc/slurm/

  slurm-master:
    image: ghcr.io/reframe-hpc/slurm-master-ubuntu:22.04
    hostname: slurm-master
    healthcheck:
        test: ["CMD-SHELL", "service slurmctld status"]
        interval: 10s
        timeout: 10s
        retries: 5
    links:
      - slurmdbd
    volumes:
      - munge-etc:/etc/munge
      - slurm-etc:/etc/slurm
    depends_on:
      munge-key-generator:
          condition: service_healthy
      slurmdbd:
          condition: service_healthy

    environment:
      - SLURM_CPUS_ON_NODE=1

  frontend:
    image: slurm-reframe
    build:
      context: examples/tutorial/dockerfiles/slurm-cluster/reframe
      args:
        REFRAME_REPO: reframe-hpc
        REFRAME_TAG: develop
    container_name: frontend
    hostname: login
    user: admin
    volumes:
      - munge-etc:/etc/munge
      - slurm-etc:/etc/slurm
      - shared-home:/home/admin:rw
      - shared-scratch:/scratch:rw
      - type: bind
        source: ./examples
        target: /home/admin/reframe-examples
    links:
      - slurm-master
    depends_on:
      munge-key-generator:
        condition: service_healthy
      slurm-master:
        condition: service_healthy
      node0:
        condition: service_started
      node1:
        condition: service_started
      node2:
        condition: service_started

  node0:
    image: ghcr.io/reframe-hpc/slurm-node-ubuntu:22.04
    hostname: nid00
    container_name: slurm-node0
    volumes:
      - munge-etc:/etc/munge
      - slurm-etc:/etc/slurm
      - shared-home:/home/admin
      - shared-scratch:/scratch:rw
    environment:
      - SLURM_NODENAME=nid00
    depends_on:
      munge-key-generator:
          condition: service_healthy
      slurm-master:
          condition: service_healthy
    links:
      - slurm-master

  node1:
    image: ghcr.io/reframe-hpc/slurm-node-ubuntu:22.04
    hostname: nid01
    container_name: slurm-node1
    volumes:
      - munge-etc:/etc/munge
      - slurm-etc:/etc/slurm
      - shared-home:/home/admin
      - shared-scratch:/scratch:rw
    environment:
      - SLURM_NODENAME=nid01
    depends_on:
      munge-key-generator:
          condition: service_healthy
      slurm-master:
          condition: service_healthy
    links:
      - slurm-master

  node2:
    image: ghcr.io/reframe-hpc/slurm-node-ubuntu:22.04
    hostname: nid02
    container_name: slurm-node2
    volumes:
      - munge-etc:/etc/munge
      - slurm-etc:/etc/slurm
      - shared-home:/home/admin
      - shared-scratch:/scratch:rw
    environment:
      - SLURM_NODENAME=nid02
    depends_on:
      munge-key-generator:
          condition: service_healthy
      slurm-master:
          condition: service_healthy
    links:
      - slurm-master

volumes:
  munge-etc:
  slurm-etc:
  shared-home:
  shared-scratch:
