# Copyright 2016-2025 Swiss National Supercomputing Centre (CSCS/ETH Zurich)
# ReFrame Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: BSD-3-Clause

systems:
- name: tutorialsys
  descr: Example system
  hostnames: ['myhost']
  partitions:
  - name: default
    descr: Example partition
    scheduler: local
    launcher: local
    environs: ['baseline']
environments:
- name: baseline
  features: ['stream']